### ISSUE TITLE
Please check if netty-epoll function is applied in addb-lettuce

### ISSUE THREAD

**Issue by hshs1103** [addb-swstarlab/addb-lettuce#1]
lettuce provides event handling like epoll.(https://github.com/lettuce-io/lettuce-core/wiki/Native-Transports)

It seems that addb_lettuce does not currently use netty-epoll.

For better performance, please provide the ability to use netty-epoll.

**Comment by arbc139** [comment]
I think this issue should be moved to 'addb-loader' repository.
https://github.com/addb-swstarlab/addb-loader/issues

Please move this issue to 'addb-loader' repository.
